### ISSUE TITLE
[Bug]: Game crashes when starting to make 1.16.5 new world

### ISSUE THREAD

**Issue by Velkheim01** [Mrbysco/CamoCreepers#1]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

forge-36.2.18

### Mod version

CamoCreepers-1.16.5-1.1.0

### Java version

1.8.0_51, Oracle Corporation

### Issue Description

When I went to start a single player world from the main menu, instead of pulling up the world creation screen the game lagged briefly (around 1-2 minutes) before crashing.

### Additional Information

[crash-2021-12-05_12.23.49-client.txt](https://github.com/Mrbysco/CamoCreepers/files/7656646/crash-2021-12-05_12.23.49-client.txt)

**Comment by Mrbysco** [comment]
I fixed this issue in 1.18 and have backported the fix to both 1.17.1 and 1.16.5 :)

**Comment by Velkheim01** [comment]
Yay thank you :)
